PARSER_BEGIN(PhoneParser)
import java.io.*;
public class PhoneParser {
  public static void main(String[] args) {
    Reader sr = new StringReader(args[0]);
    PhoneParser p = new PhoneParser(sr);
    try {
      StringBuffer number = p.PhoneNumber();
      System.out.println("The number is " + number);
    } catch (ParseException pe) {
      pe.printStackTrace();
    }
  }
}
PARSER_END(PhoneParser)
TOKEN : {
  <FOUR_DIGITS : (<DIGITS>){4}>
  | <THREE_DIGITS : (<DIGITS>){3}>
  | <#DIGITS : ["0"-"9"]>
}
StringBuffer PhoneNumber() : {
  StringBuffer number = new StringBuffer();
}
{
  <THREE_DIGITS> {number.append(token.image);}
  "-" <THREE_DIGITS> {number.append(token.image);}
  "-" <FOUR_DIGITS> {number.append(token.image);}
  <EOF> {return number;}
}
