//     Copyright 2007 Hao Sun
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License. 
// You may obtain a copy of the License at 
//
//     http://www.apache.org/licenses/LICENSE-2.0 
//
// Unless required by applicable law or agreed to in writing, 
// software distributed under the License is distributed on an 
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
// either express or implied. See the License for the specific language 
// governing permissions and limitations under the License.

/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package editor.controller.parser.java;

public interface JavaParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int LINE_COMMENT = 7;
  int MULTI_LINE_COMMENT = 8;
  int DECIMAL_LITERAL = 10;
  int HEX_LITERAL = 11;
  int OCTAL_LITERAL = 12;
  int FLOATING_POINT_LITERAL = 13;
  int EXPONENT = 14;
  int CHARACTER_LITERAL = 15;
  int STRING_LITERAL = 16;
  int ESCAPESEQ = 17;
  int ID_OR_KEYWORD = 18;
  int LETTER = 19;
  int DIGIT = 20;
  int LPAREN = 21;
  int RPAREN = 22;
  int LBRACE = 23;
  int RBRACE = 24;
  int LBRACKET = 25;
  int RBRACKET = 26;
  int SEMICOLON = 27;
  int COMMA = 28;
  int DOT = 29;
  int ASSIGN = 30;
  int GT = 31;
  int LT = 32;
  int BANG = 33;
  int TILDE = 34;
  int HOOK = 35;
  int COLON = 36;
  int EQ = 37;
  int LE = 38;
  int GE = 39;
  int NE = 40;
  int SC_OR = 41;
  int SC_AND = 42;
  int INCR = 43;
  int DECR = 44;
  int PLUS = 45;
  int MINUS = 46;
  int STAR = 47;
  int SLASH = 48;
  int BIT_AND = 49;
  int BIT_OR = 50;
  int XOR = 51;
  int REM = 52;
  int LSHIFT = 53;
  int RSIGNEDSHIFT = 54;
  int RUNSIGNEDSHIFT = 55;
  int PLUSASSIGN = 56;
  int MINUSASSIGN = 57;
  int STARASSIGN = 58;
  int SLASHASSIGN = 59;
  int ANDASSIGN = 60;
  int ORASSIGN = 61;
  int XORASSIGN = 62;
  int REMASSIGN = 63;
  int LSHIFTASSIGN = 64;
  int RSIGNEDSHIFTASSIGN = 65;
  int RUNSIGNEDSHIFTASSIGN = 66;

  int DEFAULT = 0;
  int IN_MULTI_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ESCAPESEQ>",
    "<ID_OR_KEYWORD>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
