/* Generated By:JavaCC: Do not edit this line. cppparserConstants.java */
public interface cppparserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int NUMBERCONSTANT = 12;
  int CHARACTER = 13;
  int STRING = 14;
  int ID_OR_KEYWORD = 15;
  int CATCHALL = 16;

  int DEFAULT = 0;
  int IN_COMMENT = 1;
  int PREPROCESSOR_OUTPUT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"#\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"\\n\"",
    "<token of kind 11>",
    "<NUMBERCONSTANT>",
    "<CHARACTER>",
    "<STRING>",
    "<ID_OR_KEYWORD>",
    "<CATCHALL>",
  };

}
