/* Generated By:JJTree&JavaCC: Do not edit this line. JavaParserConstants.java */
package tm.javaLang.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PEDAGOGICALMARKUP_DISPLAY_SPECIFIC = 1;
  /** RegularExpression Id. */
  int PEDAGOGICALMARKUP_HIDE_SPECIFIC = 2;
  /** RegularExpression Id. */
  int PEDAGOGICALMARKUP_OTHER = 3;
  /** RegularExpression Id. */
  int PEDAGOGICALMARKUP_INVISIBLE_ALL = 4;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 16;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 17;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 18;
  /** RegularExpression Id. */
  int ABSTRACT = 20;
  /** RegularExpression Id. */
  int ASSERT = 21;
  /** RegularExpression Id. */
  int BOOLEAN = 22;
  /** RegularExpression Id. */
  int BREAK = 23;
  /** RegularExpression Id. */
  int BYTE = 24;
  /** RegularExpression Id. */
  int CASE = 25;
  /** RegularExpression Id. */
  int CATCH = 26;
  /** RegularExpression Id. */
  int CHAR = 27;
  /** RegularExpression Id. */
  int CLASS = 28;
  /** RegularExpression Id. */
  int CONST = 29;
  /** RegularExpression Id. */
  int CONTINUE = 30;
  /** RegularExpression Id. */
  int _DEFAULT = 31;
  /** RegularExpression Id. */
  int DO = 32;
  /** RegularExpression Id. */
  int DOUBLE = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int EXTENDS = 35;
  /** RegularExpression Id. */
  int FALSE = 36;
  /** RegularExpression Id. */
  int FINAL = 37;
  /** RegularExpression Id. */
  int FINALLY = 38;
  /** RegularExpression Id. */
  int FLOAT = 39;
  /** RegularExpression Id. */
  int FOR = 40;
  /** RegularExpression Id. */
  int GOTO = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int IMPLEMENTS = 43;
  /** RegularExpression Id. */
  int IMPORT = 44;
  /** RegularExpression Id. */
  int INSTANCEOF = 45;
  /** RegularExpression Id. */
  int INT = 46;
  /** RegularExpression Id. */
  int INTERFACE = 47;
  /** RegularExpression Id. */
  int LONG = 48;
  /** RegularExpression Id. */
  int NATIVE = 49;
  /** RegularExpression Id. */
  int NEW = 50;
  /** RegularExpression Id. */
  int NULL = 51;
  /** RegularExpression Id. */
  int PACKAGE = 52;
  /** RegularExpression Id. */
  int PRIVATE = 53;
  /** RegularExpression Id. */
  int PROTECTED = 54;
  /** RegularExpression Id. */
  int PUBLIC = 55;
  /** RegularExpression Id. */
  int RETURN = 56;
  /** RegularExpression Id. */
  int SHORT = 57;
  /** RegularExpression Id. */
  int STATIC = 58;
  /** RegularExpression Id. */
  int SUPER = 59;
  /** RegularExpression Id. */
  int SWITCH = 60;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 61;
  /** RegularExpression Id. */
  int THIS = 62;
  /** RegularExpression Id. */
  int THROW = 63;
  /** RegularExpression Id. */
  int THROWS = 64;
  /** RegularExpression Id. */
  int TRANSIENT = 65;
  /** RegularExpression Id. */
  int TRUE = 66;
  /** RegularExpression Id. */
  int TRY = 67;
  /** RegularExpression Id. */
  int VOID = 68;
  /** RegularExpression Id. */
  int VOLATILE = 69;
  /** RegularExpression Id. */
  int WHILE = 70;
  /** RegularExpression Id. */
  int STRICTFP = 71;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 72;
  /** RegularExpression Id. */
  int HEX_LITERAL = 73;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 74;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 75;
  /** RegularExpression Id. */
  int EXPONENT = 76;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 77;
  /** RegularExpression Id. */
  int STRING_LITERAL = 78;
  /** RegularExpression Id. */
  int ESCAPESEQ = 79;
  /** RegularExpression Id. */
  int IDENTIFIER = 80;
  /** RegularExpression Id. */
  int LETTER = 81;
  /** RegularExpression Id. */
  int DIGIT = 82;
  /** RegularExpression Id. */
  int LPAREN = 83;
  /** RegularExpression Id. */
  int RPAREN = 84;
  /** RegularExpression Id. */
  int LBRACE = 85;
  /** RegularExpression Id. */
  int RBRACE = 86;
  /** RegularExpression Id. */
  int LBRACKET = 87;
  /** RegularExpression Id. */
  int RBRACKET = 88;
  /** RegularExpression Id. */
  int SEMICOLON = 89;
  /** RegularExpression Id. */
  int COMMA = 90;
  /** RegularExpression Id. */
  int DOT = 91;
  /** RegularExpression Id. */
  int ASSIGN = 92;
  /** RegularExpression Id. */
  int GT = 93;
  /** RegularExpression Id. */
  int LT = 94;
  /** RegularExpression Id. */
  int BANG = 95;
  /** RegularExpression Id. */
  int TILDE = 96;
  /** RegularExpression Id. */
  int HOOK = 97;
  /** RegularExpression Id. */
  int COLON = 98;
  /** RegularExpression Id. */
  int EQ = 99;
  /** RegularExpression Id. */
  int LE = 100;
  /** RegularExpression Id. */
  int GE = 101;
  /** RegularExpression Id. */
  int NE = 102;
  /** RegularExpression Id. */
  int SC_OR = 103;
  /** RegularExpression Id. */
  int SC_AND = 104;
  /** RegularExpression Id. */
  int INCR = 105;
  /** RegularExpression Id. */
  int DECR = 106;
  /** RegularExpression Id. */
  int PLUS = 107;
  /** RegularExpression Id. */
  int MINUS = 108;
  /** RegularExpression Id. */
  int STAR = 109;
  /** RegularExpression Id. */
  int SLASH = 110;
  /** RegularExpression Id. */
  int BIT_AND = 111;
  /** RegularExpression Id. */
  int BIT_OR = 112;
  /** RegularExpression Id. */
  int XOR = 113;
  /** RegularExpression Id. */
  int REM = 114;
  /** RegularExpression Id. */
  int LSHIFT = 115;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 116;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 117;
  /** RegularExpression Id. */
  int PLUSASSIGN = 118;
  /** RegularExpression Id. */
  int MINUSASSIGN = 119;
  /** RegularExpression Id. */
  int STARASSIGN = 120;
  /** RegularExpression Id. */
  int SLASHASSIGN = 121;
  /** RegularExpression Id. */
  int ANDASSIGN = 122;
  /** RegularExpression Id. */
  int ORASSIGN = 123;
  /** RegularExpression Id. */
  int XORASSIGN = 124;
  /** RegularExpression Id. */
  int REMASSIGN = 125;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 126;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 127;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 128;

  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_PEDAGOGICAL_COMMENT = 3;
  /** Lexical state. */
  int DEFAULT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<PEDAGOGICALMARKUP_DISPLAY_SPECIFIC>",
    "<PEDAGOGICALMARKUP_HIDE_SPECIFIC>",
    "\"/*#\"",
    "\"/*#I\"",
    "\"*/\"",
    "\"\\n\"",
    "<token of kind 7>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 14>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 19>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ESCAPESEQ>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
