/* Generated By:JavaCC: Do not edit this line. ConfTesterParserConstants.java */
package tm.confTester ;

public interface ConfTesterParserConstants {

  int EOF = 0;
  int ANY = 7;
  int COMPILE = 8;
  int ENDL = 9;
  int ERROR = 10;
  int EXPECT = 11;
  int EQUALS = 12;
  int EXECUTE = 13;
  int FILE = 14;
  int THIS = 15;
  int MATCHES = 16;
  int NO = 17;
  int WITH = 18;
  int INPUT = 19;
  int OUTPUT = 20;
  int STRING = 21;
  int SLASHSTRING = 22;
  int SIMPLEESCAPESEQ = 23;
  int UCODENAME = 24;
  int HEXQUAD = 25;
  int HEXDIG = 26;
  int UNKNOWN_WORD = 27;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;
  int IN_C_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"/*!\"",
    "\"//!\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"*/\"",
    "\"any\"",
    "\"compile\"",
    "\"endl\"",
    "<ERROR>",
    "<EXPECT>",
    "<EQUALS>",
    "<EXECUTE>",
    "\"file\"",
    "\"this\"",
    "<MATCHES>",
    "\"no\"",
    "\"with\"",
    "<INPUT>",
    "<OUTPUT>",
    "<STRING>",
    "<SLASHSTRING>",
    "<SIMPLEESCAPESEQ>",
    "<UCODENAME>",
    "<HEXQUAD>",
    "<HEXDIG>",
    "<UNKNOWN_WORD>",
    "<token of kind 28>",
    "<token of kind 29>",
  };

}
