/* Generated By:JavaCC: Do not edit this line. PreprocessorConstants.java */
package tm.cpp.preprocessor ;

public interface PreprocessorConstants {

  int EOF = 0;
  int PEDAGOGICALMARKUP2 = 1;
  int PEDAGOGICALMARKUP3 = 2;
  int PEDAGOGICALMARKUP4 = 3;
  int KEEP_SPACE = 7;
  int CSTYLECOMMENTSTART = 8;
  int NEWLINE = 9;
  int LINECOMMENTSTART = 10;
  int STARTDIRECTIVE = 11;
  int PPINCLUDE = 17;
  int PPIF = 18;
  int PPIFDEF = 19;
  int PPIFNDEF = 20;
  int PPELIF = 21;
  int PPELSE = 22;
  int PPENDIF = 23;
  int PPDEFINE = 24;
  int PPUNDEF = 25;
  int PPLINE = 26;
  int PPERROR = 27;
  int PPPRAGMA = 28;
  int UNEXPECTED = 29;
  int DQFILENAME = 30;
  int AQFILENAME = 31;
  int KEEP_KEYWORD = 32;
  int KEEP_NCONST = 33;
  int INT = 34;
  int INTSUFFIX = 35;
  int FLOATCONST = 36;
  int LOCAL_FLOATCONST = 37;
  int DIGITS = 38;
  int EXPPART = 39;
  int KEEP_ACONST = 40;
  int CHARACTER = 41;
  int STRING = 42;
  int SIMPLEESCAPESEQ = 43;
  int OCTALESCAPESEQ = 44;
  int HEXESCAPESEQ = 45;
  int UCODENAME = 46;
  int HEXQUAD = 47;
  int HEXDIG = 48;
  int KEEP_ID = 49;
  int KEEP_REST = 50;

  int AFTERINCLUDE = 0;
  int DIRECTIVE0 = 1;
  int IN_C_COMMENT = 2;
  int IN_LINE_COMMENT = 3;
  int IN_PEDAGOGICAL_COMMENT = 4;
  int MIDLINE = 5;
  int DEFAULT = 6;

  String[] tokenImage = {
    "<EOF>",
    "<PEDAGOGICALMARKUP2>",
    "<PEDAGOGICALMARKUP3>",
    "\"/*#\"",
    "\"*/\"",
    "\"\\n\"",
    "<token of kind 6>",
    "<KEEP_SPACE>",
    "\"/*\"",
    "<NEWLINE>",
    "\"//\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 13>",
    "\"*/\"",
    "<token of kind 15>",
    "<token of kind 16>",
    "\"include\"",
    "\"if\"",
    "\"ifdef\"",
    "\"ifndef\"",
    "\"elif\"",
    "\"else\"",
    "\"endif\"",
    "\"define\"",
    "\"undef\"",
    "\"line\"",
    "\"error\"",
    "\"pragma\"",
    "<UNEXPECTED>",
    "<DQFILENAME>",
    "<AQFILENAME>",
    "<KEEP_KEYWORD>",
    "<KEEP_NCONST>",
    "<INT>",
    "<INTSUFFIX>",
    "<FLOATCONST>",
    "<LOCAL_FLOATCONST>",
    "<DIGITS>",
    "<EXPPART>",
    "<KEEP_ACONST>",
    "<CHARACTER>",
    "<STRING>",
    "<SIMPLEESCAPESEQ>",
    "<OCTALESCAPESEQ>",
    "<HEXESCAPESEQ>",
    "<UCODENAME>",
    "<HEXQUAD>",
    "<HEXDIG>",
    "<KEEP_ID>",
    "<KEEP_REST>",
  };

}
