/* Generated By:JavaCC: Do not edit this line. JavaParserVisitor.java Version 5.0 */
package tm.javaLang.parser;

public interface JavaParserVisitor
{
  public Object visit(SimpleNode node, Object data);
}
/* JavaCC - OriginalChecksum=d0df50d3e136a26564c04463ce3c1c36 (do not edit this line) */
