/* Generated By:JJTree&JavaCC: Do not edit this line. JavaParserConstants.java */
package tm.javaLang.parser;

public interface JavaParserConstants {

  int EOF = 0;
  int PEDAGOGICALMARKUP_DISPLAY_SPECIFIC = 1;
  int PEDAGOGICALMARKUP_HIDE_SPECIFIC = 2;
  int PEDAGOGICALMARKUP_INVISIBLE_ALL = 3;
  int PEDAGOGICALMARKUP_OTHER = 4;
  int SINGLE_LINE_COMMENT = 17;
  int FORMAL_COMMENT = 18;
  int MULTI_LINE_COMMENT = 19;
  int ABSTRACT = 21;
  int ASSERT = 22;
  int BOOLEAN = 23;
  int BREAK = 24;
  int BYTE = 25;
  int CASE = 26;
  int CATCH = 27;
  int CHAR = 28;
  int CLASS = 29;
  int CONST = 30;
  int CONTINUE = 31;
  int _DEFAULT = 32;
  int DO = 33;
  int DOUBLE = 34;
  int ELSE = 35;
  int EXTENDS = 36;
  int FALSE = 37;
  int FINAL = 38;
  int FINALLY = 39;
  int FLOAT = 40;
  int FOR = 41;
  int GOTO = 42;
  int IF = 43;
  int IMPLEMENTS = 44;
  int IMPORT = 45;
  int INSTANCEOF = 46;
  int INT = 47;
  int INTERFACE = 48;
  int LONG = 49;
  int NATIVE = 50;
  int NEW = 51;
  int NULL = 52;
  int PACKAGE = 53;
  int PRIVATE = 54;
  int PROTECTED = 55;
  int PUBLIC = 56;
  int RETURN = 57;
  int SHORT = 58;
  int STATIC = 59;
  int SUPER = 60;
  int SWITCH = 61;
  int SYNCHRONIZED = 62;
  int THIS = 63;
  int THROW = 64;
  int THROWS = 65;
  int TRANSIENT = 66;
  int TRUE = 67;
  int TRY = 68;
  int VOID = 69;
  int VOLATILE = 70;
  int WHILE = 71;
  int STRICTFP = 72;
  int DECIMAL_LITERAL = 73;
  int HEX_LITERAL = 74;
  int OCTAL_LITERAL = 75;
  int FLOATING_POINT_LITERAL = 76;
  int EXPONENT = 77;
  int CHARACTER_LITERAL = 78;
  int STRING_LITERAL = 79;
  int ESCAPESEQ = 80;
  int IDENTIFIER = 81;
  int LETTER = 82;
  int DIGIT = 83;
  int LPAREN = 84;
  int RPAREN = 85;
  int LBRACE = 86;
  int RBRACE = 87;
  int LBRACKET = 88;
  int RBRACKET = 89;
  int SEMICOLON = 90;
  int COMMA = 91;
  int DOT = 92;
  int ASSIGN = 93;
  int GT = 94;
  int LT = 95;
  int BANG = 96;
  int TILDE = 97;
  int HOOK = 98;
  int COLON = 99;
  int EQ = 100;
  int LE = 101;
  int GE = 102;
  int NE = 103;
  int SC_OR = 104;
  int SC_AND = 105;
  int INCR = 106;
  int DECR = 107;
  int PLUS = 108;
  int MINUS = 109;
  int STAR = 110;
  int SLASH = 111;
  int BIT_AND = 112;
  int BIT_OR = 113;
  int XOR = 114;
  int REM = 115;
  int LSHIFT = 116;
  int RSIGNEDSHIFT = 117;
  int RUNSIGNEDSHIFT = 118;
  int PLUSASSIGN = 119;
  int MINUSASSIGN = 120;
  int STARASSIGN = 121;
  int SLASHASSIGN = 122;
  int ANDASSIGN = 123;
  int ORASSIGN = 124;
  int XORASSIGN = 125;
  int REMASSIGN = 126;
  int LSHIFTASSIGN = 127;
  int RSIGNEDSHIFTASSIGN = 128;
  int RUNSIGNEDSHIFTASSIGN = 129;

  int IN_MULTI_LINE_COMMENT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_SINGLE_LINE_COMMENT = 2;
  int INVISIBLE = 3;
  int IN_PEDAGOGICAL_COMMENT = 4;
  int DEFAULT = 5;

  String[] tokenImage = {
    "<EOF>",
    "<PEDAGOGICALMARKUP_DISPLAY_SPECIFIC>",
    "<PEDAGOGICALMARKUP_HIDE_SPECIFIC>",
    "\"/*#I\"",
    "\"/*#\"",
    "\"*/\"",
    "\"\\n\"",
    "<token of kind 7>",
    "\"*/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 15>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 20>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"strictfp\"",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<ESCAPESEQ>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
