/* Generated By:JavaCC: Do not edit this line. RegexParserConstants.java */
package visreed.extension.regex.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RegexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int STAR = 6;
  /** RegularExpression Id. */
  int QUESTION_MARK = 7;
  /** RegularExpression Id. */
  int ALTERNATION = 8;
  /** RegularExpression Id. */
  int OPEN_PAR = 9;
  /** RegularExpression Id. */
  int CLOSE_PAR = 10;
  /** RegularExpression Id. */
  int SEMI_COLON = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int TERMINAL = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"*\"",
    "\"?\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<STRING>",
    "<DIGIT>",
    "<TERMINAL>",
  };

}
