PARSER_BEGIN(PhoneParser)
import java.io.*;
public class PhoneParser {
  public static void main(String[] args) {
    Reader sr = new StringReader(args[0]);
    PhoneParser p = new PhoneParser(sr);
    try {
      p.PhoneNumber();
    } catch (ParseException pe) {
      pe.printStackTrace();
    }
  }
}
PARSER_END(PhoneParser)
TOKEN : {
  <FOUR_DIGITS : (<DIGITS>){4}>
  | <THREE_DIGITS : (<DIGITS>){3}>
  | <#DIGITS : ["0"-"9"]>
}
void PhoneNumber() : {} {
  AreaCode() "-" <THREE_DIGITS> "-" <FOUR_DIGITS> <EOF>
}
JAVACODE
void AreaCode() {
  Token tok = getNextToken();
  if (tok.kind != THREE_DIGITS) {
    throw new ParseException("Expected an area code!");
  }
  System.out.println("Area code = " + tok.image);
}
