PARSER_BEGIN(PhoneParser)
import java.io.*;
public class PhoneParser {
  public static void main(String[] args) {
    Reader sr = new StringReader(args[0]);
    PhoneParser p = new PhoneParser(sr);
    try {
      p.PhoneNumber();
    } catch (ParseException pe) {
      pe.printStackTrace();
    }
  }
}
PARSER_END(PhoneParser)
TOKEN : {
  <FOUR_DIGITS : (<DIGITS>){4}>
  | <THREE_DIGITS : (<DIGITS>){3}>
  | <#DIGITS : ["0"-"9"]>
}
void PhoneNumber() : {} {
  (
    LOOKAHEAD({getToken(1).image.equals("123")})
      KeysvilleNumber() {System.out.println("Found a Keysville number");}
    | FarmvilleNumber() {System.out.println("Found a Farmville number");}
  ) <EOF>
}
void KeysvilleNumber() : {} {
  AreaCode() "-" <FOUR_DIGITS>
}
void FarmvilleNumber() : {} {
  AreaCode() "-" <FOUR_DIGITS> 
}
void AreaCode() : {} {
  <THREE_DIGITS> 
}
