/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package jsnoopy.parser ;

public interface ParserConstants {

  int EOF = 0;
  int STRING = 8;
  int SIMPLEESCAPESEQ = 9;
  int SHORTUCODENAME = 10;
  int HEXQUAD = 11;
  int HEXDIG = 12;
  int INTEGER_LITERAL = 13;
  int FLOATING_POINT_LITERAL = 14;
  int EXPONENT = 15;
  int IDENTIFIER = 44;
  int LETTER = 45;
  int DIGIT = 46;
  int UNEXPECTED_CHAR = 47;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"\\n\"",
    "<token of kind 7>",
    "<STRING>",
    "<SIMPLEESCAPESEQ>",
    "<SHORTUCODENAME>",
    "<HEXQUAD>",
    "<HEXDIG>",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "\">>>\"",
    "\">>\"",
    "\"<<\"",
    "\".\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"return\"",
    "\"==\"",
    "\"throw\"",
    "\"<\"",
    "\">\"",
    "\"boolean\"",
    "\"byte\"",
    "\"char\"",
    "\"double\"",
    "\"float\"",
    "\"int\"",
    "\"long\"",
    "\"short\"",
    "\"[\"",
    "\";\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"{\"",
    "\"}\"",
    "\"-\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<UNEXPECTED_CHAR>",
  };

}
