#include <math.h>

float abs (float);
float acos (float);
float asin (float);
float atan (float);
float atan2(float, float);
float ceil (float);
float cos (float);
float exp (float);
float fabs (float);
float floor(float);
float log (float);
float log10(float);
float pow (float, float);
float sin (float);
float sqrt (float);
float tan (float);

long double abs (long double);
long double acos (long double);
long double asin (long double);
long double atan (long double);
long double atan2(long double, long double);
long double ceil (long double);
long double cos (long double);
long double exp (long double);
long double fabs (long double);
long double floor(long double);
long double log (long double);
long double log10(long double);
long double pow (long double, long double);
long double sin (long double);
long double sqrt (long double);
long double tan (long double);